import type { NewActivityLog, NewAsset, NewIncident, NewThreat, NewVulnerability } from "@/db/schema";

function hoursAgo(hours: number): Date {
  return new Date(Date.now() - hours * 60 * 60 * 1000);
}

function daysAgo(days: number): Date {
  return hoursAgo(days * 24);
}

export const mockThreats: NewThreat[] = [
  {
    name: "Emotet Banking Trojan Resurgence",
    category: "Malware",
    severity: "critical",
    status: "active",
    source: "ThreatForge Global Sensor Network",
    indicator: "185.220.101.47",
    indicatorType: "IPv4",
    description:
      "Reactivated Emotet distribution campaign leveraging malicious macro-enabled documents delivered through spoofed invoice emails targeting finance teams.",
    confidence: 96,
    affectedAssets: 14,
    firstSeen: daysAgo(2),
    lastSeen: hoursAgo(1),
  },
  {
    name: "BlackCat/ALPHV Ransomware Affiliate Activity",
    category: "Ransomware",
    severity: "critical",
    status: "active",
    source: "Dark Web Intelligence Feed",
    indicator: "alphv-leaks[.]onion",
    indicatorType: "Domain",
    description:
      "Double-extortion ransomware group observed staging exfiltration infrastructure ahead of encryption deployment against manufacturing sector targets.",
    confidence: 91,
    affectedAssets: 8,
    firstSeen: daysAgo(1),
    lastSeen: hoursAgo(3),
  },
  {
    name: "Log4Shell Exploitation Attempts",
    category: "Exploit",
    severity: "high",
    status: "monitoring",
    source: "Perimeter IDS",
    indicator: "CVE-2021-44228",
    indicatorType: "CVE",
    description:
      "Automated scanning and exploitation attempts against internet-facing Java applications leveraging JNDI lookup injection.",
    confidence: 88,
    affectedAssets: 5,
    firstSeen: daysAgo(9),
    lastSeen: hoursAgo(6),
  },
  {
    name: "Cobalt Strike Beacon C2 Traffic",
    category: "Command & Control",
    severity: "critical",
    status: "contained",
    source: "Network Traffic Analytics",
    indicator: "hxxps://cdn-edge-sync[.]net/beacon",
    indicatorType: "URL",
    description:
      "Encrypted beaconing pattern consistent with Cobalt Strike malleable C2 profile detected from an internal workstation to newly registered domain.",
    confidence: 93,
    affectedAssets: 3,
    firstSeen: daysAgo(4),
    lastSeen: hoursAgo(20),
  },
  {
    name: "Credential Phishing Kit — 'MFA Fatigue'",
    category: "Phishing",
    severity: "high",
    status: "active",
    source: "Email Gateway Telemetry",
    indicator: "sso-verify-portal[.]com",
    indicatorType: "Domain",
    description:
      "Adversary-in-the-middle phishing kit harvesting credentials and session tokens by proxying legitimate SSO login pages in real time.",
    confidence: 85,
    affectedAssets: 21,
    firstSeen: hoursAgo(30),
    lastSeen: hoursAgo(2),
  },
  {
    name: "Lazarus Group Supply Chain Implant",
    category: "APT",
    severity: "critical",
    status: "monitoring",
    source: "ThreatForge Research Team",
    indicator: "a91e2f7d9c4b7e3d1f0a5c8e6b2d4f19",
    indicatorType: "SHA256",
    description:
      "Trojanized software update package attributed to Lazarus Group observed establishing persistence via scheduled tasks and DLL side-loading.",
    confidence: 97,
    affectedAssets: 2,
    firstSeen: daysAgo(6),
    lastSeen: daysAgo(1),
  },
  {
    name: "IcedID Loader Malspam Campaign",
    category: "Malware",
    severity: "medium",
    status: "mitigated",
    source: "Email Gateway Telemetry",
    indicator: "billing-docs-2024[.]xyz",
    indicatorType: "Domain",
    description:
      "Malicious ISO attachment delivering IcedID loader that facilitates follow-on ransomware deployment blocked at the email gateway.",
    confidence: 79,
    affectedAssets: 0,
    firstSeen: daysAgo(11),
    lastSeen: daysAgo(3),
  },
  {
    name: "Exposed Kubernetes Dashboard",
    category: "Misconfiguration",
    severity: "high",
    status: "active",
    source: "Cloud Security Posture Scanner",
    indicator: "10.44.12.9:8443",
    indicatorType: "IPv4:Port",
    description:
      "Unauthenticated Kubernetes dashboard exposed to the internet allowing potential cluster takeover and workload manipulation.",
    confidence: 100,
    affectedAssets: 1,
    firstSeen: hoursAgo(14),
    lastSeen: hoursAgo(1),
  },
  {
    name: "DNS Tunneling Data Exfiltration",
    category: "Data Exfiltration",
    severity: "medium",
    status: "monitoring",
    source: "Network Traffic Analytics",
    indicator: "q7f2.exfil-relay[.]info",
    indicatorType: "Domain",
    description:
      "Abnormally high volume of TXT record queries suggesting covert data exfiltration channel over DNS from finance subnet.",
    confidence: 72,
    affectedAssets: 4,
    firstSeen: daysAgo(3),
    lastSeen: hoursAgo(9),
  },
  {
    name: "Formjacking Script on Checkout Page",
    category: "Web Skimming",
    severity: "high",
    status: "contained",
    source: "Web Application Firewall",
    indicator: "assets-cdn-fast[.]top/loader.js",
    indicatorType: "URL",
    description:
      "Injected JavaScript skimmer harvesting payment card details from the customer-facing checkout flow, intercepted by WAF rule.",
    confidence: 89,
    affectedAssets: 1,
    firstSeen: daysAgo(5),
    lastSeen: daysAgo(2),
  },
  {
    name: "Brute Force Against Exposed RDP",
    category: "Credential Access",
    severity: "low",
    status: "mitigated",
    source: "Perimeter IDS",
    indicator: "45.148.10.220",
    indicatorType: "IPv4",
    description:
      "Sustained password-spraying attempts against an internet-facing RDP host, since remediated with network-level ACL restrictions.",
    confidence: 66,
    affectedAssets: 0,
    firstSeen: daysAgo(16),
    lastSeen: daysAgo(8),
  },
  {
    name: "Typosquatted Domain Registration Spike",
    category: "Brand Protection",
    severity: "informational",
    status: "monitoring",
    source: "ThreatForge Research Team",
    indicator: "threatforgе-support[.]com",
    indicatorType: "Domain",
    description:
      "Cluster of newly registered lookalike domains impersonating the corporate brand, monitored for phishing infrastructure activation.",
    confidence: 58,
    affectedAssets: 0,
    firstSeen: daysAgo(7),
    lastSeen: daysAgo(1),
  },
];

export const mockIncidents: NewIncident[] = [
  {
    title: "Ransomware Encryption Attempt on Finance File Server",
    severity: "critical",
    status: "investigating",
    assignee: "Maria Chen",
    description:
      "EDR blocked mass file encryption behavior on FIN-SRV-02 originating from a compromised service account. Lateral movement suspected.",
    mitreTactic: "Impact (T1486)",
    affectedAssets: 6,
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(1),
  },
  {
    title: "Business Email Compromise — Wire Transfer Fraud Attempt",
    severity: "high",
    status: "open",
    assignee: "David Okafor",
    description:
      "CFO mailbox rules manipulated to hide replies after attacker impersonated a vendor requesting an urgent wire transfer change.",
    mitreTactic: "Collection (T1114)",
    affectedAssets: 1,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(2),
  },
  {
    title: "Unauthorized IAM Privilege Escalation in Production AWS",
    severity: "critical",
    status: "contained",
    assignee: "Priya Sharma",
    description:
      "Compromised CI/CD access key used to attach AdministratorAccess policy to a low-privilege IAM role. Key rotated and role reverted.",
    mitreTactic: "Privilege Escalation (T1078.004)",
    affectedAssets: 3,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(5),
  },
  {
    title: "Data Exfiltration via Personal Cloud Storage",
    severity: "high",
    status: "investigating",
    assignee: "Maria Chen",
    description:
      "DLP flagged large-volume upload of engineering source code to a personal Dropbox account from a departing employee's workstation.",
    mitreTactic: "Exfiltration (T1567.002)",
    affectedAssets: 1,
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(4),
  },
  {
    title: "Malicious Insider Access to HR Database",
    severity: "medium",
    status: "resolved",
    assignee: "James Wu",
    description:
      "Anomalous off-hours access to payroll records by a contractor account; access revoked and legal notified. No data loss confirmed.",
    mitreTactic: "Collection (T1213)",
    affectedAssets: 1,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    title: "DDoS Attack Against Customer-Facing API",
    severity: "medium",
    status: "resolved",
    assignee: "David Okafor",
    description:
      "Volumetric layer 7 DDoS attack peaking at 4.2M req/min mitigated by upstream scrubbing; no customer-facing downtime recorded.",
    mitreTactic: "Impact (T1499)",
    affectedAssets: 2,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },
  {
    title: "Suspicious PowerShell Encoded Command Execution",
    severity: "high",
    status: "open",
    assignee: "Priya Sharma",
    description:
      "Obfuscated PowerShell payload executed via scheduled task on a domain controller, consistent with living-off-the-land technique.",
    mitreTactic: "Execution (T1059.001)",
    affectedAssets: 2,
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    title: "Third-Party Vendor Portal Credential Leak",
    severity: "low",
    status: "resolved",
    assignee: "James Wu",
    description:
      "Vendor support portal credentials found in a public code repository; rotated immediately with no evidence of unauthorized access.",
    mitreTactic: "Initial Access (T1078)",
    affectedAssets: 0,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
  },
];

export const mockAssets: NewAsset[] = [
  { name: "FIN-SRV-02", type: "server", ipAddress: "10.12.4.22", os: "Windows Server 2022", owner: "Finance IT", riskScore: 87, status: "at_risk", agentInstalled: true, lastSeen: hoursAgo(1) },
  { name: "prod-api-gateway-01", type: "cloud", ipAddress: "10.0.1.11", os: "Amazon Linux 2023", owner: "Platform Team", riskScore: 62, status: "at_risk", agentInstalled: true, lastSeen: hoursAgo(2) },
  { name: "DC-EAST-01", type: "server", ipAddress: "10.12.0.5", os: "Windows Server 2019", owner: "Infrastructure", riskScore: 71, status: "at_risk", agentInstalled: true, lastSeen: hoursAgo(1) },
  { name: "eng-checkout-svc", type: "container", ipAddress: "172.18.4.90", os: "Alpine Linux 3.19", owner: "Commerce Team", riskScore: 45, status: "healthy", agentInstalled: true, lastSeen: hoursAgo(3) },
  { name: "LT-MCHEN-MBP", type: "workstation", ipAddress: "10.20.3.44", os: "macOS Sonoma", owner: "Maria Chen", riskScore: 22, status: "healthy", agentInstalled: true, lastSeen: hoursAgo(1) },
  { name: "LT-DOKAFOR-WIN", type: "workstation", ipAddress: "10.20.3.51", os: "Windows 11 Pro", owner: "David Okafor", riskScore: 34, status: "healthy", agentInstalled: true, lastSeen: hoursAgo(4) },
  { name: "core-switch-hq-3", type: "network_device", ipAddress: "10.0.0.3", os: "Cisco IOS XE 17.9", owner: "Network Ops", riskScore: 18, status: "healthy", agentInstalled: false, lastSeen: hoursAgo(6) },
  { name: "vpn-gateway-eu", type: "network_device", ipAddress: "10.0.0.9", os: "pfSense 2.7", owner: "Network Ops", riskScore: 55, status: "at_risk", agentInstalled: false, lastSeen: hoursAgo(2) },
  { name: "hr-db-primary", type: "server", ipAddress: "10.12.6.15", os: "Ubuntu 22.04 LTS", owner: "People Systems", riskScore: 40, status: "healthy", agentInstalled: true, lastSeen: hoursAgo(5) },
  { name: "s3-data-lake-prod", type: "cloud", ipAddress: "n/a", os: "AWS S3", owner: "Data Engineering", riskScore: 29, status: "healthy", agentInstalled: false, lastSeen: hoursAgo(8) },
  { name: "mobile-ios-fleet-12", type: "mobile", ipAddress: "10.30.1.12", os: "iOS 17.4", owner: "Sales Team", riskScore: 15, status: "healthy", agentInstalled: true, lastSeen: daysAgo(1) },
  { name: "build-runner-04", type: "container", ipAddress: "172.18.9.14", os: "Debian 12", owner: "Platform Team", riskScore: 96, status: "compromised", agentInstalled: true, lastSeen: hoursAgo(1) },
  { name: "legacy-erp-srv", type: "server", ipAddress: "10.12.2.7", os: "Windows Server 2012 R2", owner: "Finance IT", riskScore: 91, status: "at_risk", agentInstalled: false, lastSeen: daysAgo(2) },
  { name: "LT-PSHARMA-WIN", type: "workstation", ipAddress: "10.20.3.60", os: "Windows 11 Pro", owner: "Priya Sharma", riskScore: 12, status: "healthy", agentInstalled: true, lastSeen: hoursAgo(1) },
  { name: "backup-vault-west", type: "cloud", ipAddress: "n/a", os: "Azure Blob Storage", owner: "Infrastructure", riskScore: 8, status: "healthy", agentInstalled: false, lastSeen: daysAgo(1) },
  { name: "kiosk-retail-042", type: "workstation", ipAddress: "10.40.2.18", os: "Windows 10 IoT", owner: "Retail Ops", riskScore: 0, status: "offline", agentInstalled: true, lastSeen: daysAgo(9) },
];

export const mockVulnerabilities: NewVulnerability[] = [
  { cveId: "CVE-2024-3094", title: "XZ Utils Backdoor via Malicious Upstream Tarball", severity: "critical", cvssScore: 10.0, status: "patching", affectedAsset: "build-runner-04", packageName: "xz-utils 5.6.0", publishedAt: daysAgo(20) },
  { cveId: "CVE-2021-44228", title: "Apache Log4j2 JNDI Remote Code Execution (Log4Shell)", severity: "critical", cvssScore: 10.0, status: "open", affectedAsset: "legacy-erp-srv", packageName: "log4j-core 2.14.1", publishedAt: daysAgo(60) },
  { cveId: "CVE-2023-4863", title: "libwebp Heap Buffer Overflow", severity: "high", cvssScore: 8.8, status: "patched", affectedAsset: "eng-checkout-svc", packageName: "libwebp 1.3.1", publishedAt: daysAgo(90) },
  { cveId: "CVE-2024-21626", title: "runc Container Escape via Leaked File Descriptor", severity: "critical", cvssScore: 9.1, status: "open", affectedAsset: "eng-checkout-svc", packageName: "runc 1.1.11", publishedAt: daysAgo(15) },
  { cveId: "CVE-2023-38545", title: "curl SOCKS5 Heap Buffer Overflow", severity: "medium", cvssScore: 7.5, status: "patched", affectedAsset: "prod-api-gateway-01", packageName: "curl 8.3.0", publishedAt: daysAgo(120) },
  { cveId: "CVE-2024-6387", title: "OpenSSH regreSSHion Remote Code Execution", severity: "high", cvssScore: 8.1, status: "patching", affectedAsset: "DC-EAST-01", packageName: "openssh-server 9.6", publishedAt: daysAgo(9) },
  { cveId: "CVE-2022-1388", title: "F5 BIG-IP iControl REST Authentication Bypass", severity: "critical", cvssScore: 9.8, status: "accepted_risk", affectedAsset: "vpn-gateway-eu", packageName: "F5 BIG-IP 16.1.2", publishedAt: daysAgo(400) },
  { cveId: "CVE-2023-22515", title: "Atlassian Confluence Broken Access Control", severity: "critical", cvssScore: 10.0, status: "patched", affectedAsset: "hr-db-primary", packageName: "Confluence 8.5.1", publishedAt: daysAgo(200) },
  { cveId: "CVE-2024-27198", title: "TeamCity Authentication Bypass", severity: "critical", cvssScore: 9.8, status: "open", affectedAsset: "build-runner-04", packageName: "TeamCity 2023.11.3", publishedAt: daysAgo(30) },
  { cveId: "CVE-2023-46604", title: "Apache ActiveMQ OpenWire RCE", severity: "high", cvssScore: 9.8, status: "patched", affectedAsset: "legacy-erp-srv", packageName: "ActiveMQ 5.15.15", publishedAt: daysAgo(180) },
  { cveId: "CVE-2024-23917", title: "TeamCity Server REST API Auth Bypass", severity: "medium", cvssScore: 7.2, status: "patching", affectedAsset: "build-runner-04", packageName: "TeamCity 2023.05.3", publishedAt: daysAgo(45) },
  { cveId: "CVE-2023-4966", title: "Citrix NetScaler ADC Sensitive Information Disclosure (Citrix Bleed)", severity: "high", cvssScore: 7.5, status: "patched", affectedAsset: "vpn-gateway-eu", packageName: "NetScaler ADC 13.1", publishedAt: daysAgo(150) },
];

export const mockActivity: NewActivityLog[] = [
  { actor: "ThreatForge AI Engine", action: "Detected credential phishing kit targeting SSO portal", target: "sso-verify-portal.com", severity: "high", createdAt: hoursAgo(1) },
  { actor: "Maria Chen", action: "Escalated incident to Tier 3 response team", target: "Ransomware Encryption Attempt", severity: "critical", createdAt: hoursAgo(1) },
  { actor: "EDR Agent", action: "Blocked mass file encryption process", target: "FIN-SRV-02", severity: "critical", createdAt: hoursAgo(2) },
  { actor: "Priya Sharma", action: "Rotated compromised CI/CD access key", target: "prod-aws-account-4471", severity: "high", createdAt: hoursAgo(3) },
  { actor: "ThreatForge AI Engine", action: "Correlated 14 alerts into single incident", target: "APT Lateral Movement Cluster", severity: "high", createdAt: hoursAgo(4) },
  { actor: "Vulnerability Scanner", action: "Identified new critical CVE on build infrastructure", target: "build-runner-04", severity: "critical", createdAt: hoursAgo(5) },
  { actor: "David Okafor", action: "Reverted wire transfer request pending verification", target: "Finance Mailbox", severity: "medium", createdAt: hoursAgo(6) },
  { actor: "WAF", action: "Blocked formjacking script injection attempt", target: "checkout.threatforge.io", severity: "high", createdAt: hoursAgo(8) },
  { actor: "James Wu", action: "Closed incident after confirming no data loss", target: "Malicious Insider Access", severity: "low", createdAt: daysAgo(3) },
  { actor: "ThreatForge AI Engine", action: "Updated threat confidence score based on new IOC sighting", target: "Lazarus Group Supply Chain Implant", severity: "informational", createdAt: daysAgo(1) },
  { actor: "Network Sensor", action: "Flagged anomalous DNS query volume", target: "finance-subnet-10.12.4.0/24", severity: "medium", createdAt: hoursAgo(9) },
  { actor: "IAM Policy Engine", action: "Auto-remediated over-permissioned IAM role", target: "svc-deploy-role", severity: "high", createdAt: daysAgo(1) },
];
